# Netlify configuration (static site)
[build]
  publish = "."

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Pretty URLs
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 301
